version: '3.2'
services:
  assp:
    build: .
    image: eftechcombr/assp:ASSP_2.8.1_23131
    restart: unless-stopped
    container_name: assp
    ports:
      - "25:25"
      - "587:587"
      - "465:465"
      - "2525:2525"
      - "55555:55555"
#    volumes:
#      - assp-volume:/var/db/assp/:rw
    depends_on: 
      - db
#    command: 
#      - "sleep"
#      - "10000"
  db: 
    image: docker.io/mariadb:latest
    restart: unless-stopped
#    volumes: 
#      - assp-db-volume:/var/www/mysql:rw
    env_file:
      - .env
    ports: 
      - "3306:3306"
  # clamd: 
  #   image: eftechcombr/clamav:latest
  #   restart: unless-stopped
  #   ports: 
  #     - "3310:3310"
# volumes: 
#   assp-volume:
#   assp-db-volume:
